# Generated by Django 3.2 on 2021-04-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='pic',
            field=models.ImageField(upload_to='pictures'),
        ),
    ]
