# Generated by Django 3.1.7 on 2021-06-17 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210617_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='header',
            field=models.ImageField(default='default/header.jpg', upload_to='headers'),
        ),
    ]
